name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Path filter
      id: filter
      uses: dorny/paths-filter@v2
      with:
        filters: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'
    
    - name: Build the backend Docker image and push
      if: steps.filter.outputs.backend == 'true'
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: openpro-backend
        registry: ghcr.io
        dockerfile: backend/Dockerfile
        directory: backend
        addLatest: true
        addTimestamp: true
        multiPlatform: true
        platform: linux/amd64,linux/arm64
        enableBuildKit: true
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build the frontend Docker image and push
      if: steps.filter.outputs.frontend == 'true'
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: openpro-frontend
        registry: ghcr.io
        dockerfile: frontend/Dockerfile
        directory: frontend
        addLatest: true
        addTimestamp: true
        multiPlatform: true
        platform: linux/amd64,linux/arm64
        enableBuildKit: true
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
