name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the backend Docker image and push
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: openpro-backend
        registry: ghcr.io
        dockerfile: backend/Dockerfile
        addLatest: true
        addTimestamp: true
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build the frontend Docker image and push
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: openpro-frontend
        registry: ghcr.io
        dockerfile: frontend/Dockerfile
        addLatest: true
        addTimestamp: true
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
