name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the backend Docker image
      run: docker build ./backend --file Dockerfile --tag openpro-backend:$(date +%s)
    - name: Build the frontend Docker image
      run: docker build ./frontend --file Dockerfile --tag openpro-backend:$(date +%s)
